forgot password backend functionality #12
Avdhesh-Varshney/chanakya-niti-backend pull request #24
Opened 2024-10-22 17:51 UTC by skanarul8002

please accept the pr for issue #12, previous pr#19.

2024-10-28 16:24 UTC, Avdhesh-Varshney requested changes

2024-10-28 16:24 UTC, Avdhesh-Varshney commented on middleware/fetchuser.js
> +const JWT_SECRET = process.env.JWT_SECRET || 'Skanarul$123@';
Remove this update

2024-10-28 16:39 UTC, skanarul8002 commented
@Avdhesh-Varshney , i have done your given changes request.

2024-10-29 12:03 UTC, Avdhesh-Varshney approved these changes

2024-10-29 12:04 UTC, merged

2024-10-29 12:16 UTC, skanarul8002 commented
@Avdhesh-Varshney , Please use labels gssoc-ext, levelno etc.

2024-10-29 12:18 UTC, Avdhesh-Varshney commented
> @Avdhesh-Varshney , Please use labels gssoc-ext, levelno etc.

Backend repo is not part of `gssoc-ext`

2024-10-29 12:26 UTC, skanarul8002 commented
Good mentor @Avdhesh-Varshney , frontend is part of gssoc-ext but you are not accepted the pr code due to your own deployment code problem but I give more time to solve the assigned issue. Please give value to others contributor and getting value from others. As mentor, your behaviour is not good... Please make yourself as supportive person.